title:              Our Good Times
email:              sheffield.cao23@gmail.com
description:        Memories between Qiqi and Xu.
author:             Qi&Xu
baseurl:            "/"
url:                "https://qixu1314.github.io"

# Social Profiles
twitter_username:   QiXu1314
github_username:    QiXu1314
facebook_username:  QiXu1314
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
